apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/git-repository: go    
  labels:
    build: webhook
  name: webhook
spec:
  failedBuildsHistoryLimit: 3
  successfulBuildsHistoryLimit: 3
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: webhook:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: http://git/go.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: SOURCE_REPO_ORIGIN
        value: https://gitlab.com/dstcorp/go.git
      - name: TARGET_PKG
        value: gitlab.com/dstcorp/go/cmd/projOper
      from:
        kind: ImageStreamTag
#        name: s2i-go:latest
        name: golang-builder:latest
        namespace: mch
    type: Source
  triggers:
  - github:
      secret: k90oNnpO5d2HnAnP0P5Y
    type: GitHub
  - generic:
      secret: aJ8mD2g2pxNlm7aokR8L
    type: Generic
  - type: ConfigChange
  - imageChange:
    type: ImageChange
